### ISSUE TITLE
Old WebChat version?

### ISSUE THREAD

**Issue by cwhitten** [luisalvesmartins/vschatdown#2]
Hi! I see that the version of WebChat that you are using is pretty dated. Are there plans to update any time soon?

Additionally, having all of the WebChat bits checked-in may be causing some side-effects that might be avoided by pulling it down via more traditional means. To simulate the BotFramework Protocol/Direct Line Service, was the use of https://www.npmjs.com/package/offline-directline considered? Being able to use something like this may reduce the complexity of the chat control a bit.

**Comment by luisalvesmartins** [comment]
Hi!
I did an update on the offline webchat recently and I'm using it in the botconversationdesigner. I didn't update this project. If you are using this, I can update it. At the time I was not aware of the offline-directline project, so I hacked the webchat code.

**Comment by luisalvesmartins** [comment]
Just updated it to v4.
